### ISSUE TITLE
Incompatibility with civiCRM 5.31.0?

### ISSUE THREAD

**Issue by larnoult** [mecachisenros/aws#9]
Hello,
I just upgraded to 5.31.0 (on WordPress 5.5.3).
After DB update, it created such fatal error: 
`Fatal error: Uncaught Error: Class 'Civi\Aws\Subscriber\NavigationMenu' not found in /home/parlemon/www/wp-content/uploads/civicrm/ext/aws-master/aws.php:35 Stack trace: #0 /home/parlemon/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook.php(271): aws_civicrm_config(Object(CRM_Core_Config)) #1 /home/parlemon/www/wp-content/plugins/civicrm/civicrm/CRM/Utils/Hook/WordPress.php(136): CRM_Utils_Hook->runHooks(Array, 'civicrm_config', 1, Object(CRM_Core_Config), NULL, NULL, NULL, NULL, NULL) #2 /home/parlemon/www/wp-content/plugins/civicrm/civicrm/Civi/Core/CiviEventDispatcher.php(168): CRM_Utils_Hook_WordPress->invokeViaUF(1, Object(CRM_Core_Config), NULL, NULL, NULL, NULL, NULL, 'civicrm_config') #3 /home/parlemon/www/wp-content/plugins/civicrm/civicrm/vendor/symfony/event-dispatcher/EventDispatcher.php(214): Civi\Core\CiviEventDispatcher::delegateToUF(Object(Civi\Core\Event\GenericHookEvent), 'hook_civicrm_co...', Object(Civi\Core\CiviEventDispatcher)) #4 /home/parlemon/www/wp-content/plugins/civicrm/civicrm/vendor/symf in /home/parlemon/www/wp-content/uploads/civicrm/ext/aws-master/aws.php on line 35
`
I hope a fix could come, your extension is so convenient!
Cheers,

**Comment by larnoult** [comment]
Clearing the cache solved the issue. 
If you can't access civi, you can try to do   truncate civicrm_cache in the database, and delete the "container" files in templates_c
